export const sampleRecords = [
  {
    country: "United States",
    region: "Americas",
    bondName: "US 10Y Treasury",
    currency: "USD",
    maturity: "10Y",
    couponRate: 5.44,
    bondPrice: 95.5,
    yieldToMaturity: 5.59,
    creditRating: "A+",
    debtToGdp: 80.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 4,
    policyInterestRate: 5.49,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 400,
    goldReserves: 20,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Canada",
    region: "Americas",
    bondName: "Canada 10Y Bond",
    currency: "CAD",
    maturity: "10Y",
    couponRate: 5.44,
    bondPrice: 95.5,
    yieldToMaturity: 5.59,
    creditRating: "A+",
    debtToGdp: 80.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 4,
    policyInterestRate: 5.49,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 400,
    goldReserves: 20,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Mexico",
    region: "Americas",
    bondName: "Mexico 10Y Bond",
    currency: "MXN",
    maturity: "10Y",
    couponRate: 5.44,
    bondPrice: 95.5,
    yieldToMaturity: 5.59,
    creditRating: "A+",
    debtToGdp: 80.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 4,
    policyInterestRate: 5.49,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 400,
    goldReserves: 20,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Brazil",
    region: "Americas",
    bondName: "Brazil 10Y Bond",
    currency: "BRL",
    maturity: "10Y",
    couponRate: 5.44,
    bondPrice: 95.5,
    yieldToMaturity: 5.59,
    creditRating: "A+",
    debtToGdp: 80.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 4,
    policyInterestRate: 5.49,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 400,
    goldReserves: 20,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Argentina",
    region: "Americas",
    bondName: "Argentina 10Y Bond",
    currency: "ARS",
    maturity: "10Y",
    couponRate: 5.44,
    bondPrice: 95.5,
    yieldToMaturity: 5.59,
    creditRating: "A+",
    debtToGdp: 80.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 4,
    policyInterestRate: 5.49,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 400,
    goldReserves: 20,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Chile",
    region: "Americas",
    bondName: "Chile 10Y Bond",
    currency: "CLP",
    maturity: "10Y",
    couponRate: 5.44,
    bondPrice: 95.5,
    yieldToMaturity: 5.59,
    creditRating: "A+",
    debtToGdp: 80.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 4,
    policyInterestRate: 5.49,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 400,
    goldReserves: 20,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Colombia",
    region: "Americas",
    bondName: "Colombia 10Y Bond",
    currency: "COP",
    maturity: "10Y",
    couponRate: 5.44,
    bondPrice: 95.5,
    yieldToMaturity: 5.59,
    creditRating: "A+",
    debtToGdp: 80.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 4,
    policyInterestRate: 5.49,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 400,
    goldReserves: 20,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Peru",
    region: "Americas",
    bondName: "Peru 10Y Bond",
    currency: "PEN",
    maturity: "10Y",
    couponRate: 5.44,
    bondPrice: 95.5,
    yieldToMaturity: 5.59,
    creditRating: "A+",
    debtToGdp: 80.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 4,
    policyInterestRate: 5.49,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 400,
    goldReserves: 20,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Uruguay",
    region: "Americas",
    bondName: "Uruguay 10Y Bond",
    currency: "UYU",
    maturity: "10Y",
    couponRate: 5.44,
    bondPrice: 95.5,
    yieldToMaturity: 5.59,
    creditRating: "A+",
    debtToGdp: 80.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 4,
    policyInterestRate: 5.49,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 400,
    goldReserves: 20,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Paraguay",
    region: "Americas",
    bondName: "Paraguay 10Y Bond",
    currency: "PYG",
    maturity: "10Y",
    couponRate: 5.44,
    bondPrice: 95.5,
    yieldToMaturity: 5.59,
    creditRating: "A+",
    debtToGdp: 80.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 4,
    policyInterestRate: 5.49,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 400,
    goldReserves: 20,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Ecuador",
    region: "Americas",
    bondName: "Ecuador 10Y Bond",
    currency: "USD",
    maturity: "10Y",
    couponRate: 5.44,
    bondPrice: 95.5,
    yieldToMaturity: 5.59,
    creditRating: "A+",
    debtToGdp: 80.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 4,
    policyInterestRate: 5.49,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 400,
    goldReserves: 20,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Bolivia",
    region: "Americas",
    bondName: "Bolivia 10Y Bond",
    currency: "BOB",
    maturity: "10Y",
    couponRate: 5.44,
    bondPrice: 95.5,
    yieldToMaturity: 5.59,
    creditRating: "A+",
    debtToGdp: 80.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 4,
    policyInterestRate: 5.49,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 400,
    goldReserves: 20,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Venezuela",
    region: "Americas",
    bondName: "Venezuela 10Y Bond",
    currency: "VES",
    maturity: "10Y",
    couponRate: 5.44,
    bondPrice: 95.5,
    yieldToMaturity: 5.59,
    creditRating: "A+",
    debtToGdp: 80.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 4,
    policyInterestRate: 5.49,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 400,
    goldReserves: 20,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "United Kingdom",
    region: "Europe",
    bondName: "UK 10Y Gilt",
    currency: "GBP",
    maturity: "10Y",
    couponRate: 5.01,
    bondPrice: 96.4,
    yieldToMaturity: 5.16,
    creditRating: "AA-",
    debtToGdp: 79.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.22,
    exchangeRateVolatility: 5.4,
    foreignExchangeReserves: 230,
    goldReserves: 11.5,
    cdsSpread: 59,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Germany",
    region: "Europe",
    bondName: "Germany 10Y Bund",
    currency: "EUR",
    maturity: "10Y",
    couponRate: 5.01,
    bondPrice: 96.4,
    yieldToMaturity: 5.16,
    creditRating: "AA-",
    debtToGdp: 79.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.22,
    exchangeRateVolatility: 5.4,
    foreignExchangeReserves: 230,
    goldReserves: 11.5,
    cdsSpread: 59,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "France",
    region: "Europe",
    bondName: "France 10Y OAT",
    currency: "EUR",
    maturity: "10Y",
    couponRate: 5.01,
    bondPrice: 96.4,
    yieldToMaturity: 5.16,
    creditRating: "AA-",
    debtToGdp: 79.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.22,
    exchangeRateVolatility: 5.4,
    foreignExchangeReserves: 230,
    goldReserves: 11.5,
    cdsSpread: 59,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Italy",
    region: "Europe",
    bondName: "Italy 10Y BTP",
    currency: "EUR",
    maturity: "10Y",
    couponRate: 5.01,
    bondPrice: 96.4,
    yieldToMaturity: 5.16,
    creditRating: "AA-",
    debtToGdp: 79.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.22,
    exchangeRateVolatility: 5.4,
    foreignExchangeReserves: 230,
    goldReserves: 11.5,
    cdsSpread: 59,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Spain",
    region: "Europe",
    bondName: "Spain 10Y Bonos",
    currency: "EUR",
    maturity: "10Y",
    couponRate: 5.01,
    bondPrice: 96.4,
    yieldToMaturity: 5.16,
    creditRating: "AA-",
    debtToGdp: 79.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.22,
    exchangeRateVolatility: 5.4,
    foreignExchangeReserves: 230,
    goldReserves: 11.5,
    cdsSpread: 59,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Netherlands",
    region: "Europe",
    bondName: "Netherlands 10Y Bond",
    currency: "EUR",
    maturity: "10Y",
    couponRate: 5.01,
    bondPrice: 96.4,
    yieldToMaturity: 5.16,
    creditRating: "AA-",
    debtToGdp: 79.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.22,
    exchangeRateVolatility: 5.4,
    foreignExchangeReserves: 230,
    goldReserves: 11.5,
    cdsSpread: 59,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Belgium",
    region: "Europe",
    bondName: "Belgium 10Y Bond",
    currency: "EUR",
    maturity: "10Y",
    couponRate: 5.01,
    bondPrice: 96.4,
    yieldToMaturity: 5.16,
    creditRating: "AA-",
    debtToGdp: 79.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.22,
    exchangeRateVolatility: 5.4,
    foreignExchangeReserves: 230,
    goldReserves: 11.5,
    cdsSpread: 59,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Switzerland",
    region: "Europe",
    bondName: "Switzerland 10Y Bond",
    currency: "CHF",
    maturity: "10Y",
    couponRate: 5.01,
    bondPrice: 96.4,
    yieldToMaturity: 5.16,
    creditRating: "AA-",
    debtToGdp: 79.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.22,
    exchangeRateVolatility: 5.4,
    foreignExchangeReserves: 230,
    goldReserves: 11.5,
    cdsSpread: 59,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Sweden",
    region: "Europe",
    bondName: "Sweden 10Y Bond",
    currency: "SEK",
    maturity: "10Y",
    couponRate: 5.01,
    bondPrice: 96.4,
    yieldToMaturity: 5.16,
    creditRating: "AA-",
    debtToGdp: 79.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.22,
    exchangeRateVolatility: 5.4,
    foreignExchangeReserves: 230,
    goldReserves: 11.5,
    cdsSpread: 59,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Norway",
    region: "Europe",
    bondName: "Norway 10Y Bond",
    currency: "NOK",
    maturity: "10Y",
    couponRate: 5.01,
    bondPrice: 96.4,
    yieldToMaturity: 5.16,
    creditRating: "AA-",
    debtToGdp: 79.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.22,
    exchangeRateVolatility: 5.4,
    foreignExchangeReserves: 230,
    goldReserves: 11.5,
    cdsSpread: 59,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Denmark",
    region: "Europe",
    bondName: "Denmark 10Y Bond",
    currency: "DKK",
    maturity: "10Y",
    couponRate: 5.01,
    bondPrice: 96.4,
    yieldToMaturity: 5.16,
    creditRating: "AA-",
    debtToGdp: 79.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.22,
    exchangeRateVolatility: 5.4,
    foreignExchangeReserves: 230,
    goldReserves: 11.5,
    cdsSpread: 59,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Finland",
    region: "Europe",
    bondName: "Finland 10Y Bond",
    currency: "EUR",
    maturity: "10Y",
    couponRate: 5.01,
    bondPrice: 96.4,
    yieldToMaturity: 5.16,
    creditRating: "AA-",
    debtToGdp: 79.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.22,
    exchangeRateVolatility: 5.4,
    foreignExchangeReserves: 230,
    goldReserves: 11.5,
    cdsSpread: 59,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Austria",
    region: "Europe",
    bondName: "Austria 10Y Bond",
    currency: "EUR",
    maturity: "10Y",
    couponRate: 5.01,
    bondPrice: 96.4,
    yieldToMaturity: 5.16,
    creditRating: "AA-",
    debtToGdp: 79.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.22,
    exchangeRateVolatility: 5.4,
    foreignExchangeReserves: 230,
    goldReserves: 11.5,
    cdsSpread: 59,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Ireland",
    region: "Europe",
    bondName: "Ireland 10Y Bond",
    currency: "EUR",
    maturity: "10Y",
    couponRate: 5.01,
    bondPrice: 96.4,
    yieldToMaturity: 5.16,
    creditRating: "AA-",
    debtToGdp: 79.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.22,
    exchangeRateVolatility: 5.4,
    foreignExchangeReserves: 230,
    goldReserves: 11.5,
    cdsSpread: 59,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Portugal",
    region: "Europe",
    bondName: "Portugal 10Y Bond",
    currency: "EUR",
    maturity: "10Y",
    couponRate: 5.01,
    bondPrice: 96.4,
    yieldToMaturity: 5.16,
    creditRating: "AA-",
    debtToGdp: 79.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.22,
    exchangeRateVolatility: 5.4,
    foreignExchangeReserves: 230,
    goldReserves: 11.5,
    cdsSpread: 59,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Greece",
    region: "Europe",
    bondName: "Greece 10Y Bond",
    currency: "EUR",
    maturity: "10Y",
    couponRate: 5.01,
    bondPrice: 96.4,
    yieldToMaturity: 5.16,
    creditRating: "AA-",
    debtToGdp: 79.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.22,
    exchangeRateVolatility: 5.4,
    foreignExchangeReserves: 230,
    goldReserves: 11.5,
    cdsSpread: 59,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Poland",
    region: "Europe",
    bondName: "Poland 10Y Bond",
    currency: "PLN",
    maturity: "10Y",
    couponRate: 5.01,
    bondPrice: 96.4,
    yieldToMaturity: 5.16,
    creditRating: "AA-",
    debtToGdp: 79.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.22,
    exchangeRateVolatility: 5.4,
    foreignExchangeReserves: 230,
    goldReserves: 11.5,
    cdsSpread: 59,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Czech Republic",
    region: "Europe",
    bondName: "Czech Republic 10Y Bond",
    currency: "CZK",
    maturity: "10Y",
    couponRate: 5.01,
    bondPrice: 96.4,
    yieldToMaturity: 5.16,
    creditRating: "AA-",
    debtToGdp: 79.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.22,
    exchangeRateVolatility: 5.4,
    foreignExchangeReserves: 230,
    goldReserves: 11.5,
    cdsSpread: 59,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Hungary",
    region: "Europe",
    bondName: "Hungary 10Y Bond",
    currency: "HUF",
    maturity: "10Y",
    couponRate: 5.01,
    bondPrice: 96.4,
    yieldToMaturity: 5.16,
    creditRating: "AA-",
    debtToGdp: 79.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.22,
    exchangeRateVolatility: 5.4,
    foreignExchangeReserves: 230,
    goldReserves: 11.5,
    cdsSpread: 59,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Romania",
    region: "Europe",
    bondName: "Romania 10Y Bond",
    currency: "RON",
    maturity: "10Y",
    couponRate: 5.01,
    bondPrice: 96.4,
    yieldToMaturity: 5.16,
    creditRating: "AA-",
    debtToGdp: 79.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.22,
    exchangeRateVolatility: 5.4,
    foreignExchangeReserves: 230,
    goldReserves: 11.5,
    cdsSpread: 59,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Bulgaria",
    region: "Europe",
    bondName: "Bulgaria 10Y Bond",
    currency: "BGN",
    maturity: "10Y",
    couponRate: 5.01,
    bondPrice: 96.4,
    yieldToMaturity: 5.16,
    creditRating: "AA-",
    debtToGdp: 79.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.22,
    exchangeRateVolatility: 5.4,
    foreignExchangeReserves: 230,
    goldReserves: 11.5,
    cdsSpread: 59,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Slovakia",
    region: "Europe",
    bondName: "Slovakia 10Y Bond",
    currency: "EUR",
    maturity: "10Y",
    couponRate: 5.01,
    bondPrice: 96.4,
    yieldToMaturity: 5.16,
    creditRating: "AA-",
    debtToGdp: 79.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.22,
    exchangeRateVolatility: 5.4,
    foreignExchangeReserves: 230,
    goldReserves: 11.5,
    cdsSpread: 59,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Slovenia",
    region: "Europe",
    bondName: "Slovenia 10Y Bond",
    currency: "EUR",
    maturity: "10Y",
    couponRate: 5.01,
    bondPrice: 96.4,
    yieldToMaturity: 5.16,
    creditRating: "AA-",
    debtToGdp: 79.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.22,
    exchangeRateVolatility: 5.4,
    foreignExchangeReserves: 230,
    goldReserves: 11.5,
    cdsSpread: 59,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Croatia",
    region: "Europe",
    bondName: "Croatia 10Y Bond",
    currency: "HRK",
    maturity: "10Y",
    couponRate: 5.01,
    bondPrice: 96.4,
    yieldToMaturity: 5.16,
    creditRating: "AA-",
    debtToGdp: 79.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.22,
    exchangeRateVolatility: 5.4,
    foreignExchangeReserves: 230,
    goldReserves: 11.5,
    cdsSpread: 59,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Serbia",
    region: "Europe",
    bondName: "Serbia 10Y Bond",
    currency: "RSD",
    maturity: "10Y",
    couponRate: 5.01,
    bondPrice: 96.4,
    yieldToMaturity: 5.16,
    creditRating: "AA-",
    debtToGdp: 79.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.22,
    exchangeRateVolatility: 5.4,
    foreignExchangeReserves: 230,
    goldReserves: 11.5,
    cdsSpread: 59,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Montenegro",
    region: "Europe",
    bondName: "Montenegro 10Y Bond",
    currency: "EUR",
    maturity: "10Y",
    couponRate: 5.01,
    bondPrice: 96.4,
    yieldToMaturity: 5.16,
    creditRating: "AA-",
    debtToGdp: 79.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.22,
    exchangeRateVolatility: 5.4,
    foreignExchangeReserves: 230,
    goldReserves: 11.5,
    cdsSpread: 59,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "North Macedonia",
    region: "Europe",
    bondName: "North Macedonia 10Y Bond",
    currency: "MKD",
    maturity: "10Y",
    couponRate: 5.01,
    bondPrice: 96.4,
    yieldToMaturity: 5.16,
    creditRating: "AA-",
    debtToGdp: 79.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.22,
    exchangeRateVolatility: 5.4,
    foreignExchangeReserves: 230,
    goldReserves: 11.5,
    cdsSpread: 59,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "China",
    region: "Asia",
    bondName: "China 10Y Government Bond",
    currency: "CNY",
    maturity: "10Y",
    couponRate: 5.46,
    bondPrice: 95.5,
    yieldToMaturity: 5.61,
    creditRating: "A+",
    debtToGdp: 80.9,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 4,
    policyInterestRate: 5.5,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 650,
    goldReserves: 19.5,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Japan",
    region: "Asia",
    bondName: "Japan 10Y JGB",
    currency: "JPY",
    maturity: "10Y",
    couponRate: 5.46,
    bondPrice: 95.5,
    yieldToMaturity: 5.61,
    creditRating: "A+",
    debtToGdp: 80.9,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 4,
    policyInterestRate: 5.5,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 650,
    goldReserves: 19.5,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "South Korea",
    region: "Asia",
    bondName: "South Korea 10Y Bond",
    currency: "KRW",
    maturity: "10Y",
    couponRate: 5.46,
    bondPrice: 95.5,
    yieldToMaturity: 5.61,
    creditRating: "A+",
    debtToGdp: 80.9,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 4,
    policyInterestRate: 5.5,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 650,
    goldReserves: 19.5,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "India",
    region: "Asia",
    bondName: "India 10Y G-Sec",
    currency: "INR",
    maturity: "10Y",
    couponRate: 5.46,
    bondPrice: 95.5,
    yieldToMaturity: 5.61,
    creditRating: "A+",
    debtToGdp: 80.9,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 4,
    policyInterestRate: 5.5,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 650,
    goldReserves: 19.5,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Indonesia",
    region: "Asia",
    bondName: "Indonesia 10Y Bond",
    currency: "IDR",
    maturity: "10Y",
    couponRate: 5.46,
    bondPrice: 95.5,
    yieldToMaturity: 5.61,
    creditRating: "A+",
    debtToGdp: 80.9,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 4,
    policyInterestRate: 5.5,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 650,
    goldReserves: 19.5,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Thailand",
    region: "Asia",
    bondName: "Thailand 10Y Bond",
    currency: "THB",
    maturity: "10Y",
    couponRate: 5.46,
    bondPrice: 95.5,
    yieldToMaturity: 5.61,
    creditRating: "A+",
    debtToGdp: 80.9,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 4,
    policyInterestRate: 5.5,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 650,
    goldReserves: 19.5,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Vietnam",
    region: "Asia",
    bondName: "Vietnam 10Y Bond",
    currency: "VND",
    maturity: "10Y",
    couponRate: 5.46,
    bondPrice: 95.5,
    yieldToMaturity: 5.61,
    creditRating: "A+",
    debtToGdp: 80.9,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 4,
    policyInterestRate: 5.5,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 650,
    goldReserves: 19.5,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Malaysia",
    region: "Asia",
    bondName: "Malaysia 10Y Bond",
    currency: "MYR",
    maturity: "10Y",
    couponRate: 5.46,
    bondPrice: 95.5,
    yieldToMaturity: 5.61,
    creditRating: "A+",
    debtToGdp: 80.9,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 4,
    policyInterestRate: 5.5,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 650,
    goldReserves: 19.5,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Singapore",
    region: "Asia",
    bondName: "Singapore 10Y SGS",
    currency: "SGD",
    maturity: "10Y",
    couponRate: 5.46,
    bondPrice: 95.5,
    yieldToMaturity: 5.61,
    creditRating: "A+",
    debtToGdp: 80.9,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 4,
    policyInterestRate: 5.5,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 650,
    goldReserves: 19.5,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Philippines",
    region: "Asia",
    bondName: "Philippines 10Y Bond",
    currency: "PHP",
    maturity: "10Y",
    couponRate: 5.46,
    bondPrice: 95.5,
    yieldToMaturity: 5.61,
    creditRating: "A+",
    debtToGdp: 80.9,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 4,
    policyInterestRate: 5.5,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 650,
    goldReserves: 19.5,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Pakistan",
    region: "Asia",
    bondName: "Pakistan 10Y Bond",
    currency: "PKR",
    maturity: "10Y",
    couponRate: 5.46,
    bondPrice: 95.5,
    yieldToMaturity: 5.61,
    creditRating: "A+",
    debtToGdp: 80.9,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 4,
    policyInterestRate: 5.5,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 650,
    goldReserves: 19.5,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Bangladesh",
    region: "Asia",
    bondName: "Bangladesh 10Y Bond",
    currency: "BDT",
    maturity: "10Y",
    couponRate: 5.46,
    bondPrice: 95.5,
    yieldToMaturity: 5.61,
    creditRating: "A+",
    debtToGdp: 80.9,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 4,
    policyInterestRate: 5.5,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 650,
    goldReserves: 19.5,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Sri Lanka",
    region: "Asia",
    bondName: "Sri Lanka 10Y Bond",
    currency: "LKR",
    maturity: "10Y",
    couponRate: 5.46,
    bondPrice: 95.5,
    yieldToMaturity: 5.61,
    creditRating: "A+",
    debtToGdp: 80.9,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 4,
    policyInterestRate: 5.5,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 650,
    goldReserves: 19.5,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Nepal",
    region: "Asia",
    bondName: "Nepal 10Y Bond",
    currency: "NPR",
    maturity: "10Y",
    couponRate: 5.46,
    bondPrice: 95.5,
    yieldToMaturity: 5.61,
    creditRating: "A+",
    debtToGdp: 80.9,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 4,
    policyInterestRate: 5.5,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 650,
    goldReserves: 19.5,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Mongolia",
    region: "Asia",
    bondName: "Mongolia 10Y Bond",
    currency: "MNT",
    maturity: "10Y",
    couponRate: 5.46,
    bondPrice: 95.5,
    yieldToMaturity: 5.61,
    creditRating: "A+",
    debtToGdp: 80.9,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 4,
    policyInterestRate: 5.5,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 650,
    goldReserves: 19.5,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Kazakhstan",
    region: "Asia",
    bondName: "Kazakhstan 10Y Bond",
    currency: "KZT",
    maturity: "10Y",
    couponRate: 5.46,
    bondPrice: 95.5,
    yieldToMaturity: 5.61,
    creditRating: "A+",
    debtToGdp: 80.9,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 4,
    policyInterestRate: 5.5,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 650,
    goldReserves: 19.5,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Uzbekistan",
    region: "Asia",
    bondName: "Uzbekistan 10Y Bond",
    currency: "UZS",
    maturity: "10Y",
    couponRate: 5.46,
    bondPrice: 95.5,
    yieldToMaturity: 5.61,
    creditRating: "A+",
    debtToGdp: 80.9,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 4,
    policyInterestRate: 5.5,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 650,
    goldReserves: 19.5,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Azerbaijan",
    region: "Asia",
    bondName: "Azerbaijan 10Y Bond",
    currency: "AZN",
    maturity: "10Y",
    couponRate: 5.46,
    bondPrice: 95.5,
    yieldToMaturity: 5.61,
    creditRating: "A+",
    debtToGdp: 80.9,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 4,
    policyInterestRate: 5.5,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 650,
    goldReserves: 19.5,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Georgia",
    region: "Asia",
    bondName: "Georgia 10Y Bond",
    currency: "GEL",
    maturity: "10Y",
    couponRate: 5.46,
    bondPrice: 95.5,
    yieldToMaturity: 5.61,
    creditRating: "A+",
    debtToGdp: 80.9,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 4,
    policyInterestRate: 5.5,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 650,
    goldReserves: 19.5,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Armenia",
    region: "Asia",
    bondName: "Armenia 10Y Bond",
    currency: "AMD",
    maturity: "10Y",
    couponRate: 5.46,
    bondPrice: 95.5,
    yieldToMaturity: 5.61,
    creditRating: "A+",
    debtToGdp: 80.9,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 4,
    policyInterestRate: 5.5,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 650,
    goldReserves: 19.5,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Saudi Arabia",
    region: "Middle East",
    bondName: "Saudi Arabia 10Y Bond",
    currency: "SAR",
    maturity: "10Y",
    couponRate: 5.6,
    bondPrice: 95.3,
    yieldToMaturity: 5.75,
    creditRating: "A+",
    debtToGdp: 82.4,
    fiscalDeficitToGdp: 3.4,
    inflationRate: 4.1,
    policyInterestRate: 5.66,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 420,
    goldReserves: 6.3,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "United Arab Emirates",
    region: "Middle East",
    bondName: "UAE 10Y Bond",
    currency: "AED",
    maturity: "10Y",
    couponRate: 5.6,
    bondPrice: 95.3,
    yieldToMaturity: 5.75,
    creditRating: "A+",
    debtToGdp: 82.4,
    fiscalDeficitToGdp: 3.4,
    inflationRate: 4.1,
    policyInterestRate: 5.66,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 420,
    goldReserves: 6.3,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Qatar",
    region: "Middle East",
    bondName: "Qatar 10Y Bond",
    currency: "QAR",
    maturity: "10Y",
    couponRate: 5.6,
    bondPrice: 95.3,
    yieldToMaturity: 5.75,
    creditRating: "A+",
    debtToGdp: 82.4,
    fiscalDeficitToGdp: 3.4,
    inflationRate: 4.1,
    policyInterestRate: 5.66,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 420,
    goldReserves: 6.3,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Kuwait",
    region: "Middle East",
    bondName: "Kuwait 10Y Bond",
    currency: "KWD",
    maturity: "10Y",
    couponRate: 5.6,
    bondPrice: 95.3,
    yieldToMaturity: 5.75,
    creditRating: "A+",
    debtToGdp: 82.4,
    fiscalDeficitToGdp: 3.4,
    inflationRate: 4.1,
    policyInterestRate: 5.66,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 420,
    goldReserves: 6.3,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Bahrain",
    region: "Middle East",
    bondName: "Bahrain 10Y Bond",
    currency: "BHD",
    maturity: "10Y",
    couponRate: 5.6,
    bondPrice: 95.3,
    yieldToMaturity: 5.75,
    creditRating: "A+",
    debtToGdp: 82.4,
    fiscalDeficitToGdp: 3.4,
    inflationRate: 4.1,
    policyInterestRate: 5.66,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 420,
    goldReserves: 6.3,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Oman",
    region: "Middle East",
    bondName: "Oman 10Y Bond",
    currency: "OMR",
    maturity: "10Y",
    couponRate: 5.6,
    bondPrice: 95.3,
    yieldToMaturity: 5.75,
    creditRating: "A+",
    debtToGdp: 82.4,
    fiscalDeficitToGdp: 3.4,
    inflationRate: 4.1,
    policyInterestRate: 5.66,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 420,
    goldReserves: 6.3,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Israel",
    region: "Middle East",
    bondName: "Israel 10Y Bond",
    currency: "ILS",
    maturity: "10Y",
    couponRate: 5.6,
    bondPrice: 95.3,
    yieldToMaturity: 5.75,
    creditRating: "A+",
    debtToGdp: 82.4,
    fiscalDeficitToGdp: 3.4,
    inflationRate: 4.1,
    policyInterestRate: 5.66,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 420,
    goldReserves: 6.3,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Jordan",
    region: "Middle East",
    bondName: "Jordan 10Y Bond",
    currency: "JOD",
    maturity: "10Y",
    couponRate: 5.6,
    bondPrice: 95.3,
    yieldToMaturity: 5.75,
    creditRating: "A+",
    debtToGdp: 82.4,
    fiscalDeficitToGdp: 3.4,
    inflationRate: 4.1,
    policyInterestRate: 5.66,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 420,
    goldReserves: 6.3,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Lebanon",
    region: "Middle East",
    bondName: "Lebanon 10Y Bond",
    currency: "LBP",
    maturity: "10Y",
    couponRate: 5.6,
    bondPrice: 95.3,
    yieldToMaturity: 5.75,
    creditRating: "A+",
    debtToGdp: 82.4,
    fiscalDeficitToGdp: 3.4,
    inflationRate: 4.1,
    policyInterestRate: 5.66,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 420,
    goldReserves: 6.3,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Iraq",
    region: "Middle East",
    bondName: "Iraq 10Y Bond",
    currency: "IQD",
    maturity: "10Y",
    couponRate: 5.6,
    bondPrice: 95.3,
    yieldToMaturity: 5.75,
    creditRating: "A+",
    debtToGdp: 82.4,
    fiscalDeficitToGdp: 3.4,
    inflationRate: 4.1,
    policyInterestRate: 5.66,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 420,
    goldReserves: 6.3,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "South Africa",
    region: "Africa",
    bondName: "South Africa 10Y Bond",
    currency: "ZAR",
    maturity: "10Y",
    couponRate: 5.68,
    bondPrice: 95.2,
    yieldToMaturity: 5.83,
    creditRating: "A+",
    debtToGdp: 83.4,
    fiscalDeficitToGdp: 3.5,
    inflationRate: 4.1,
    policyInterestRate: 5.72,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 80,
    goldReserves: 1.2,
    cdsSpread: 71,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Nigeria",
    region: "Africa",
    bondName: "Nigeria 10Y Bond",
    currency: "NGN",
    maturity: "10Y",
    couponRate: 5.68,
    bondPrice: 95.2,
    yieldToMaturity: 5.83,
    creditRating: "A+",
    debtToGdp: 83.4,
    fiscalDeficitToGdp: 3.5,
    inflationRate: 4.1,
    policyInterestRate: 5.72,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 80,
    goldReserves: 1.2,
    cdsSpread: 71,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Egypt",
    region: "Africa",
    bondName: "Egypt 10Y Bond",
    currency: "EGP",
    maturity: "10Y",
    couponRate: 5.68,
    bondPrice: 95.2,
    yieldToMaturity: 5.83,
    creditRating: "A+",
    debtToGdp: 83.4,
    fiscalDeficitToGdp: 3.5,
    inflationRate: 4.1,
    policyInterestRate: 5.72,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 80,
    goldReserves: 1.2,
    cdsSpread: 71,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Morocco",
    region: "Africa",
    bondName: "Morocco 10Y Bond",
    currency: "MAD",
    maturity: "10Y",
    couponRate: 5.68,
    bondPrice: 95.2,
    yieldToMaturity: 5.83,
    creditRating: "A+",
    debtToGdp: 83.4,
    fiscalDeficitToGdp: 3.5,
    inflationRate: 4.1,
    policyInterestRate: 5.72,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 80,
    goldReserves: 1.2,
    cdsSpread: 71,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Algeria",
    region: "Africa",
    bondName: "Algeria 10Y Bond",
    currency: "DZD",
    maturity: "10Y",
    couponRate: 5.68,
    bondPrice: 95.2,
    yieldToMaturity: 5.83,
    creditRating: "A+",
    debtToGdp: 83.4,
    fiscalDeficitToGdp: 3.5,
    inflationRate: 4.1,
    policyInterestRate: 5.72,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 80,
    goldReserves: 1.2,
    cdsSpread: 71,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Tunisia",
    region: "Africa",
    bondName: "Tunisia 10Y Bond",
    currency: "TND",
    maturity: "10Y",
    couponRate: 5.68,
    bondPrice: 95.2,
    yieldToMaturity: 5.83,
    creditRating: "A+",
    debtToGdp: 83.4,
    fiscalDeficitToGdp: 3.5,
    inflationRate: 4.1,
    policyInterestRate: 5.72,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 80,
    goldReserves: 1.2,
    cdsSpread: 71,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Kenya",
    region: "Africa",
    bondName: "Kenya 10Y Bond",
    currency: "KES",
    maturity: "10Y",
    couponRate: 5.68,
    bondPrice: 95.2,
    yieldToMaturity: 5.83,
    creditRating: "A+",
    debtToGdp: 83.4,
    fiscalDeficitToGdp: 3.5,
    inflationRate: 4.1,
    policyInterestRate: 5.72,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 80,
    goldReserves: 1.2,
    cdsSpread: 71,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Ethiopia",
    region: "Africa",
    bondName: "Ethiopia 10Y Bond",
    currency: "ETB",
    maturity: "10Y",
    couponRate: 5.68,
    bondPrice: 95.2,
    yieldToMaturity: 5.83,
    creditRating: "A+",
    debtToGdp: 83.4,
    fiscalDeficitToGdp: 3.5,
    inflationRate: 4.1,
    policyInterestRate: 5.72,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 80,
    goldReserves: 1.2,
    cdsSpread: 71,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Ghana",
    region: "Africa",
    bondName: "Ghana 10Y Bond",
    currency: "GHS",
    maturity: "10Y",
    couponRate: 5.68,
    bondPrice: 95.2,
    yieldToMaturity: 5.83,
    creditRating: "A+",
    debtToGdp: 83.4,
    fiscalDeficitToGdp: 3.5,
    inflationRate: 4.1,
    policyInterestRate: 5.72,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 80,
    goldReserves: 1.2,
    cdsSpread: 71,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Tanzania",
    region: "Africa",
    bondName: "Tanzania 10Y Bond",
    currency: "TZS",
    maturity: "10Y",
    couponRate: 5.68,
    bondPrice: 95.2,
    yieldToMaturity: 5.83,
    creditRating: "A+",
    debtToGdp: 83.4,
    fiscalDeficitToGdp: 3.5,
    inflationRate: 4.1,
    policyInterestRate: 5.72,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 80,
    goldReserves: 1.2,
    cdsSpread: 71,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Uganda",
    region: "Africa",
    bondName: "Uganda 10Y Bond",
    currency: "UGX",
    maturity: "10Y",
    couponRate: 5.68,
    bondPrice: 95.2,
    yieldToMaturity: 5.83,
    creditRating: "A+",
    debtToGdp: 83.4,
    fiscalDeficitToGdp: 3.5,
    inflationRate: 4.1,
    policyInterestRate: 5.72,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 80,
    goldReserves: 1.2,
    cdsSpread: 71,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Angola",
    region: "Africa",
    bondName: "Angola 10Y Bond",
    currency: "AOA",
    maturity: "10Y",
    couponRate: 5.68,
    bondPrice: 95.2,
    yieldToMaturity: 5.83,
    creditRating: "A+",
    debtToGdp: 83.4,
    fiscalDeficitToGdp: 3.5,
    inflationRate: 4.1,
    policyInterestRate: 5.72,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 80,
    goldReserves: 1.2,
    cdsSpread: 71,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Mozambique",
    region: "Africa",
    bondName: "Mozambique 10Y Bond",
    currency: "MZN",
    maturity: "10Y",
    couponRate: 5.68,
    bondPrice: 95.2,
    yieldToMaturity: 5.83,
    creditRating: "A+",
    debtToGdp: 83.4,
    fiscalDeficitToGdp: 3.5,
    inflationRate: 4.1,
    policyInterestRate: 5.72,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 80,
    goldReserves: 1.2,
    cdsSpread: 71,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Senegal",
    region: "Africa",
    bondName: "Senegal 10Y Bond",
    currency: "XOF",
    maturity: "10Y",
    couponRate: 5.68,
    bondPrice: 95.2,
    yieldToMaturity: 5.83,
    creditRating: "A+",
    debtToGdp: 83.4,
    fiscalDeficitToGdp: 3.5,
    inflationRate: 4.1,
    policyInterestRate: 5.72,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 80,
    goldReserves: 1.2,
    cdsSpread: 71,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Cameroon",
    region: "Africa",
    bondName: "Cameroon 10Y Bond",
    currency: "XAF",
    maturity: "10Y",
    couponRate: 5.68,
    bondPrice: 95.2,
    yieldToMaturity: 5.83,
    creditRating: "A+",
    debtToGdp: 83.4,
    fiscalDeficitToGdp: 3.5,
    inflationRate: 4.1,
    policyInterestRate: 5.72,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 80,
    goldReserves: 1.2,
    cdsSpread: 71,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Zambia",
    region: "Africa",
    bondName: "Zambia 10Y Bond",
    currency: "ZMW",
    maturity: "10Y",
    couponRate: 5.68,
    bondPrice: 95.2,
    yieldToMaturity: 5.83,
    creditRating: "A+",
    debtToGdp: 83.4,
    fiscalDeficitToGdp: 3.5,
    inflationRate: 4.1,
    policyInterestRate: 5.72,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 80,
    goldReserves: 1.2,
    cdsSpread: 71,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Zimbabwe",
    region: "Africa",
    bondName: "Zimbabwe 10Y Bond",
    currency: "ZWL",
    maturity: "10Y",
    couponRate: 5.68,
    bondPrice: 95.2,
    yieldToMaturity: 5.83,
    creditRating: "A+",
    debtToGdp: 83.4,
    fiscalDeficitToGdp: 3.5,
    inflationRate: 4.1,
    policyInterestRate: 5.72,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 80,
    goldReserves: 1.2,
    cdsSpread: 71,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Botswana",
    region: "Africa",
    bondName: "Botswana 10Y Bond",
    currency: "BWP",
    maturity: "10Y",
    couponRate: 5.68,
    bondPrice: 95.2,
    yieldToMaturity: 5.83,
    creditRating: "A+",
    debtToGdp: 83.4,
    fiscalDeficitToGdp: 3.5,
    inflationRate: 4.1,
    policyInterestRate: 5.72,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 80,
    goldReserves: 1.2,
    cdsSpread: 71,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Namibia",
    region: "Africa",
    bondName: "Namibia 10Y Bond",
    currency: "NAD",
    maturity: "10Y",
    couponRate: 5.68,
    bondPrice: 95.2,
    yieldToMaturity: 5.83,
    creditRating: "A+",
    debtToGdp: 83.4,
    fiscalDeficitToGdp: 3.5,
    inflationRate: 4.1,
    policyInterestRate: 5.72,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 80,
    goldReserves: 1.2,
    cdsSpread: 71,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Mauritius",
    region: "Africa",
    bondName: "Mauritius 10Y Bond",
    currency: "MUR",
    maturity: "10Y",
    couponRate: 5.68,
    bondPrice: 95.2,
    yieldToMaturity: 5.83,
    creditRating: "A+",
    debtToGdp: 83.4,
    fiscalDeficitToGdp: 3.5,
    inflationRate: 4.1,
    policyInterestRate: 5.72,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 80,
    goldReserves: 1.2,
    cdsSpread: 71,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Madagascar",
    region: "Africa",
    bondName: "Madagascar 10Y Bond",
    currency: "MGA",
    maturity: "10Y",
    couponRate: 5.68,
    bondPrice: 95.2,
    yieldToMaturity: 5.83,
    creditRating: "A+",
    debtToGdp: 83.4,
    fiscalDeficitToGdp: 3.5,
    inflationRate: 4.1,
    policyInterestRate: 5.72,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 80,
    goldReserves: 1.2,
    cdsSpread: 71,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Rwanda",
    region: "Africa",
    bondName: "Rwanda 10Y Bond",
    currency: "RWF",
    maturity: "10Y",
    couponRate: 5.68,
    bondPrice: 95.2,
    yieldToMaturity: 5.83,
    creditRating: "A+",
    debtToGdp: 83.4,
    fiscalDeficitToGdp: 3.5,
    inflationRate: 4.1,
    policyInterestRate: 5.72,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 80,
    goldReserves: 1.2,
    cdsSpread: 71,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Burundi",
    region: "Africa",
    bondName: "Burundi 10Y Bond",
    currency: "BIF",
    maturity: "10Y",
    couponRate: 5.68,
    bondPrice: 95.2,
    yieldToMaturity: 5.83,
    creditRating: "A+",
    debtToGdp: 83.4,
    fiscalDeficitToGdp: 3.5,
    inflationRate: 4.1,
    policyInterestRate: 5.72,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 80,
    goldReserves: 1.2,
    cdsSpread: 71,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Australia",
    region: "Oceania",
    bondName: "Australia 10Y Bond",
    currency: "AUD",
    maturity: "10Y",
    couponRate: 5.36,
    bondPrice: 95.6,
    yieldToMaturity: 5.51,
    creditRating: "A+",
    debtToGdp: 79.9,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.38,
    exchangeRateVolatility: 6.2,
    foreignExchangeReserves: 30,
    goldReserves: 0.6,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "New Zealand",
    region: "Oceania",
    bondName: "New Zealand 10Y Bond",
    currency: "NZD",
    maturity: "10Y",
    couponRate: 5.36,
    bondPrice: 95.6,
    yieldToMaturity: 5.51,
    creditRating: "A+",
    debtToGdp: 79.9,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.38,
    exchangeRateVolatility: 6.2,
    foreignExchangeReserves: 30,
    goldReserves: 0.6,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Papua New Guinea",
    region: "Oceania",
    bondName: "Papua New Guinea 10Y Bond",
    currency: "PGK",
    maturity: "10Y",
    couponRate: 5.36,
    bondPrice: 95.6,
    yieldToMaturity: 5.51,
    creditRating: "A+",
    debtToGdp: 79.9,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.38,
    exchangeRateVolatility: 6.2,
    foreignExchangeReserves: 30,
    goldReserves: 0.6,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Fiji",
    region: "Oceania",
    bondName: "Fiji 10Y Bond",
    currency: "FJD",
    maturity: "10Y",
    couponRate: 5.36,
    bondPrice: 95.6,
    yieldToMaturity: 5.51,
    creditRating: "A+",
    debtToGdp: 79.9,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.38,
    exchangeRateVolatility: 6.2,
    foreignExchangeReserves: 30,
    goldReserves: 0.6,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Solomon Islands",
    region: "Oceania",
    bondName: "Solomon Islands 10Y Bond",
    currency: "SBD",
    maturity: "10Y",
    couponRate: 5.36,
    bondPrice: 95.6,
    yieldToMaturity: 5.51,
    creditRating: "A+",
    debtToGdp: 79.9,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.38,
    exchangeRateVolatility: 6.2,
    foreignExchangeReserves: 30,
    goldReserves: 0.6,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Vanuatu",
    region: "Oceania",
    bondName: "Vanuatu 10Y Bond",
    currency: "VUV",
    maturity: "10Y",
    couponRate: 5.36,
    bondPrice: 95.6,
    yieldToMaturity: 5.51,
    creditRating: "A+",
    debtToGdp: 79.9,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.38,
    exchangeRateVolatility: 6.2,
    foreignExchangeReserves: 30,
    goldReserves: 0.6,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Samoa",
    region: "Oceania",
    bondName: "Samoa 10Y Bond",
    currency: "WST",
    maturity: "10Y",
    couponRate: 5.36,
    bondPrice: 95.6,
    yieldToMaturity: 5.51,
    creditRating: "A+",
    debtToGdp: 79.9,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.38,
    exchangeRateVolatility: 6.2,
    foreignExchangeReserves: 30,
    goldReserves: 0.6,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Tonga",
    region: "Oceania",
    bondName: "Tonga 10Y Bond",
    currency: "TOP",
    maturity: "10Y",
    couponRate: 5.36,
    bondPrice: 95.6,
    yieldToMaturity: 5.51,
    creditRating: "A+",
    debtToGdp: 79.9,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.38,
    exchangeRateVolatility: 6.2,
    foreignExchangeReserves: 30,
    goldReserves: 0.6,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Kiribati",
    region: "Oceania",
    bondName: "Kiribati 10Y Bond",
    currency: "AUD",
    maturity: "10Y",
    couponRate: 5.36,
    bondPrice: 95.6,
    yieldToMaturity: 5.51,
    creditRating: "A+",
    debtToGdp: 79.9,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.38,
    exchangeRateVolatility: 6.2,
    foreignExchangeReserves: 30,
    goldReserves: 0.6,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Marshall Islands",
    region: "Oceania",
    bondName: "Marshall Islands 10Y Bond",
    currency: "USD",
    maturity: "10Y",
    couponRate: 5.36,
    bondPrice: 95.6,
    yieldToMaturity: 5.51,
    creditRating: "A+",
    debtToGdp: 79.9,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.38,
    exchangeRateVolatility: 6.2,
    foreignExchangeReserves: 30,
    goldReserves: 0.6,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03
  }
];
