export const sampleRecords = [
  {
    country: "United States",
    region: "Americas",
    bondName: "US 10Y Treasury",
    bondType: "localCurrency",
    currency: "USD",
    maturity: "10Y",
    couponRate: 5.44,
    bondPrice: 95.5,
    yieldToMaturity: 4.56,
    creditRating: "A+",
    debtToGdp: 80.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 4,
    policyInterestRate: 5.49,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 400,
    goldReserves: 20,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: screenshot; yield basis: local currency.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Canada",
    region: "Americas",
    bondName: "Canada 10Y Bond",
    bondType: "localCurrency",
    currency: "CAD",
    maturity: "10Y",
    couponRate: 5.44,
    bondPrice: 95.5,
    yieldToMaturity: 3.51,
    creditRating: "A+",
    debtToGdp: 80.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 4,
    policyInterestRate: 5.49,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 400,
    goldReserves: 20,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: screenshot; yield basis: local currency.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Mexico",
    region: "Americas",
    bondName: "Mexico 10Y Bond",
    bondType: "localCurrency",
    currency: "MXN",
    maturity: "10Y",
    couponRate: 5.44,
    bondPrice: 95.5,
    yieldToMaturity: 9.16,
    creditRating: "A+",
    debtToGdp: 80.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 4,
    policyInterestRate: 5.49,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 400,
    goldReserves: 20,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: screenshot/public source; yield basis: local currency.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Brazil",
    region: "Americas",
    bondName: "Brazil 10Y Bond",
    bondType: "localCurrency",
    currency: "BRL",
    maturity: "10Y",
    couponRate: 5.44,
    bondPrice: 95.5,
    yieldToMaturity: 14.67,
    creditRating: "A+",
    debtToGdp: 80.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 4,
    policyInterestRate: 5.49,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 400,
    goldReserves: 20,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: screenshot; yield basis: local currency.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Argentina",
    region: "Americas",
    bondName: "Argentina 10Y Bond",
    bondType: "eurobond",
    currency: "USD",
    maturity: "10Y",
    couponRate: 5.44,
    bondPrice: 95.5,
    yieldToMaturity: 10.5,
    creditRating: "A+",
    debtToGdp: 80.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 4,
    policyInterestRate: 5.49,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 400,
    goldReserves: 20,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: estimate; yield basis: USD bond.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Chile",
    region: "Americas",
    bondName: "Chile 10Y Bond",
    bondType: "localCurrency",
    currency: "CLP",
    maturity: "10Y",
    couponRate: 5.44,
    bondPrice: 95.5,
    yieldToMaturity: 5.62,
    creditRating: "A+",
    debtToGdp: 80.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 4,
    policyInterestRate: 5.49,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 400,
    goldReserves: 20,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: screenshot; yield basis: local currency.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Colombia",
    region: "Americas",
    bondName: "Colombia 10Y Bond",
    bondType: "localCurrency",
    currency: "COP",
    maturity: "10Y",
    couponRate: 5.44,
    bondPrice: 95.5,
    yieldToMaturity: 12.25,
    creditRating: "A+",
    debtToGdp: 80.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 4,
    policyInterestRate: 5.49,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 400,
    goldReserves: 20,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: screenshot; yield basis: local currency.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Peru",
    region: "Americas",
    bondName: "Peru 10Y Bond",
    bondType: "localCurrency",
    currency: "PEN",
    maturity: "10Y",
    couponRate: 5.44,
    bondPrice: 95.5,
    yieldToMaturity: 5.07,
    creditRating: "A+",
    debtToGdp: 80.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 4,
    policyInterestRate: 5.49,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 400,
    goldReserves: 20,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: screenshot; yield basis: local currency.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Uruguay",
    region: "Americas",
    bondName: "Uruguay 10Y Bond",
    bondType: "localCurrency",
    currency: "UYU",
    maturity: "10Y",
    couponRate: 5.44,
    bondPrice: 95.5,
    yieldToMaturity: 8.8,
    creditRating: "A+",
    debtToGdp: 80.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 4,
    policyInterestRate: 5.49,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 400,
    goldReserves: 20,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: estimate; yield basis: local currency.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Paraguay",
    region: "Americas",
    bondName: "Paraguay 10Y Bond",
    bondType: "eurobond",
    currency: "USD",
    maturity: "10Y",
    couponRate: 5.44,
    bondPrice: 95.5,
    yieldToMaturity: 6,
    creditRating: "A+",
    debtToGdp: 80.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 4,
    policyInterestRate: 5.49,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 400,
    goldReserves: 20,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: estimate; yield basis: USD bond.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Ecuador",
    region: "Americas",
    bondName: "Ecuador 10Y Bond",
    bondType: "eurobond",
    currency: "USD",
    maturity: "10Y",
    couponRate: 5.44,
    bondPrice: 95.5,
    yieldToMaturity: 12,
    creditRating: "A+",
    debtToGdp: 80.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 4,
    policyInterestRate: 5.49,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 400,
    goldReserves: 20,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: estimate; yield basis: USD bond.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Bolivia",
    region: "Americas",
    bondName: "Bolivia 10Y Bond",
    bondType: "eurobond",
    currency: "USD",
    maturity: "10Y",
    couponRate: 5.44,
    bondPrice: 95.5,
    yieldToMaturity: 16,
    creditRating: "A+",
    debtToGdp: 80.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 4,
    policyInterestRate: 5.49,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 400,
    goldReserves: 20,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: estimate; yield basis: USD bond.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "United Kingdom",
    region: "Europe",
    bondName: "UK 10Y Gilt",
    bondType: "localCurrency",
    currency: "GBP",
    maturity: "10Y",
    couponRate: 5.01,
    bondPrice: 96.4,
    yieldToMaturity: 4.9,
    creditRating: "AA-",
    debtToGdp: 79.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.22,
    exchangeRateVolatility: 5.4,
    foreignExchangeReserves: 230,
    goldReserves: 11.5,
    cdsSpread: 59,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: public source; yield basis: local currency.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Germany",
    region: "Europe",
    bondName: "Germany 10Y Bund",
    bondType: "localCurrency",
    currency: "EUR",
    maturity: "10Y",
    couponRate: 5.01,
    bondPrice: 96.4,
    yieldToMaturity: 3.06,
    creditRating: "AA-",
    debtToGdp: 79.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.22,
    exchangeRateVolatility: 5.4,
    foreignExchangeReserves: 230,
    goldReserves: 11.5,
    cdsSpread: 59,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: screenshot; yield basis: local currency.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "France",
    region: "Europe",
    bondName: "France 10Y OAT",
    bondType: "localCurrency",
    currency: "EUR",
    maturity: "10Y",
    couponRate: 5.01,
    bondPrice: 96.4,
    yieldToMaturity: 3.73,
    creditRating: "AA-",
    debtToGdp: 79.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.22,
    exchangeRateVolatility: 5.4,
    foreignExchangeReserves: 230,
    goldReserves: 11.5,
    cdsSpread: 59,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: screenshot; yield basis: local currency.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Italy",
    region: "Europe",
    bondName: "Italy 10Y BTP",
    bondType: "localCurrency",
    currency: "EUR",
    maturity: "10Y",
    couponRate: 5.01,
    bondPrice: 96.4,
    yieldToMaturity: 3.84,
    creditRating: "AA-",
    debtToGdp: 79.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.22,
    exchangeRateVolatility: 5.4,
    foreignExchangeReserves: 230,
    goldReserves: 11.5,
    cdsSpread: 59,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: screenshot; yield basis: local currency.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Spain",
    region: "Europe",
    bondName: "Spain 10Y Bonos",
    bondType: "localCurrency",
    currency: "EUR",
    maturity: "10Y",
    couponRate: 5.01,
    bondPrice: 96.4,
    yieldToMaturity: 3.51,
    creditRating: "AA-",
    debtToGdp: 79.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.22,
    exchangeRateVolatility: 5.4,
    foreignExchangeReserves: 230,
    goldReserves: 11.5,
    cdsSpread: 59,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: screenshot; yield basis: local currency.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Netherlands",
    region: "Europe",
    bondName: "Netherlands 10Y Bond",
    bondType: "localCurrency",
    currency: "EUR",
    maturity: "10Y",
    couponRate: 5.01,
    bondPrice: 96.4,
    yieldToMaturity: 3.18,
    creditRating: "AA-",
    debtToGdp: 79.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.22,
    exchangeRateVolatility: 5.4,
    foreignExchangeReserves: 230,
    goldReserves: 11.5,
    cdsSpread: 59,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: screenshot; yield basis: local currency.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Belgium",
    region: "Europe",
    bondName: "Belgium 10Y Bond",
    bondType: "localCurrency",
    currency: "EUR",
    maturity: "10Y",
    couponRate: 5.01,
    bondPrice: 96.4,
    yieldToMaturity: 3.63,
    creditRating: "AA-",
    debtToGdp: 79.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.22,
    exchangeRateVolatility: 5.4,
    foreignExchangeReserves: 230,
    goldReserves: 11.5,
    cdsSpread: 59,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: screenshot; yield basis: local currency.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Switzerland",
    region: "Europe",
    bondName: "Switzerland 10Y Bond",
    bondType: "localCurrency",
    currency: "CHF",
    maturity: "10Y",
    couponRate: 5.01,
    bondPrice: 96.4,
    yieldToMaturity: 0.43,
    creditRating: "AA-",
    debtToGdp: 79.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.22,
    exchangeRateVolatility: 5.4,
    foreignExchangeReserves: 230,
    goldReserves: 11.5,
    cdsSpread: 59,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: screenshot; yield basis: local currency.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Sweden",
    region: "Europe",
    bondName: "Sweden 10Y Bond",
    bondType: "localCurrency",
    currency: "SEK",
    maturity: "10Y",
    couponRate: 5.01,
    bondPrice: 96.4,
    yieldToMaturity: 2.91,
    creditRating: "AA-",
    debtToGdp: 79.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.22,
    exchangeRateVolatility: 5.4,
    foreignExchangeReserves: 230,
    goldReserves: 11.5,
    cdsSpread: 59,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: screenshot; yield basis: local currency.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Norway",
    region: "Europe",
    bondName: "Norway 10Y Bond",
    bondType: "localCurrency",
    currency: "NOK",
    maturity: "10Y",
    couponRate: 5.01,
    bondPrice: 96.4,
    yieldToMaturity: 4.43,
    creditRating: "AA-",
    debtToGdp: 79.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.22,
    exchangeRateVolatility: 5.4,
    foreignExchangeReserves: 230,
    goldReserves: 11.5,
    cdsSpread: 59,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: screenshot; yield basis: local currency.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Denmark",
    region: "Europe",
    bondName: "Denmark 10Y Bond",
    bondType: "localCurrency",
    currency: "DKK",
    maturity: "10Y",
    couponRate: 5.01,
    bondPrice: 96.4,
    yieldToMaturity: 2.93,
    creditRating: "AA-",
    debtToGdp: 79.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.22,
    exchangeRateVolatility: 5.4,
    foreignExchangeReserves: 230,
    goldReserves: 11.5,
    cdsSpread: 59,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: screenshot; yield basis: local currency.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Finland",
    region: "Europe",
    bondName: "Finland 10Y Bond",
    bondType: "localCurrency",
    currency: "EUR",
    maturity: "10Y",
    couponRate: 5.01,
    bondPrice: 96.4,
    yieldToMaturity: 3.41,
    creditRating: "AA-",
    debtToGdp: 79.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.22,
    exchangeRateVolatility: 5.4,
    foreignExchangeReserves: 230,
    goldReserves: 11.5,
    cdsSpread: 59,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: screenshot; yield basis: local currency.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Austria",
    region: "Europe",
    bondName: "Austria 10Y Bond",
    bondType: "localCurrency",
    currency: "EUR",
    maturity: "10Y",
    couponRate: 5.01,
    bondPrice: 96.4,
    yieldToMaturity: 3.31,
    creditRating: "AA-",
    debtToGdp: 79.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.22,
    exchangeRateVolatility: 5.4,
    foreignExchangeReserves: 230,
    goldReserves: 11.5,
    cdsSpread: 59,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: screenshot; yield basis: local currency.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Ireland",
    region: "Europe",
    bondName: "Ireland 10Y Bond",
    bondType: "localCurrency",
    currency: "EUR",
    maturity: "10Y",
    couponRate: 5.01,
    bondPrice: 96.4,
    yieldToMaturity: 3.24,
    creditRating: "AA-",
    debtToGdp: 79.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.22,
    exchangeRateVolatility: 5.4,
    foreignExchangeReserves: 230,
    goldReserves: 11.5,
    cdsSpread: 59,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: screenshot; yield basis: local currency.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Portugal",
    region: "Europe",
    bondName: "Portugal 10Y Bond",
    bondType: "localCurrency",
    currency: "EUR",
    maturity: "10Y",
    couponRate: 5.01,
    bondPrice: 96.4,
    yieldToMaturity: 3.45,
    creditRating: "AA-",
    debtToGdp: 79.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.22,
    exchangeRateVolatility: 5.4,
    foreignExchangeReserves: 230,
    goldReserves: 11.5,
    cdsSpread: 59,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: screenshot; yield basis: local currency.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Greece",
    region: "Europe",
    bondName: "Greece 10Y Bond",
    bondType: "localCurrency",
    currency: "EUR",
    maturity: "10Y",
    couponRate: 5.01,
    bondPrice: 96.4,
    yieldToMaturity: 3.75,
    creditRating: "AA-",
    debtToGdp: 79.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.22,
    exchangeRateVolatility: 5.4,
    foreignExchangeReserves: 230,
    goldReserves: 11.5,
    cdsSpread: 59,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: screenshot; yield basis: local currency.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Poland",
    region: "Europe",
    bondName: "Poland 10Y Bond",
    bondType: "localCurrency",
    currency: "PLN",
    maturity: "10Y",
    couponRate: 5.01,
    bondPrice: 96.4,
    yieldToMaturity: 5.87,
    creditRating: "AA-",
    debtToGdp: 79.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.22,
    exchangeRateVolatility: 5.4,
    foreignExchangeReserves: 230,
    goldReserves: 11.5,
    cdsSpread: 59,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: screenshot; yield basis: local currency.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Czech Republic",
    region: "Europe",
    bondName: "Czech Republic 10Y Bond",
    bondType: "localCurrency",
    currency: "CZK",
    maturity: "10Y",
    couponRate: 5.01,
    bondPrice: 96.4,
    yieldToMaturity: 4.9,
    creditRating: "AA-",
    debtToGdp: 79.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.22,
    exchangeRateVolatility: 5.4,
    foreignExchangeReserves: 230,
    goldReserves: 11.5,
    cdsSpread: 59,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: screenshot; yield basis: local currency.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Hungary",
    region: "Europe",
    bondName: "Hungary 10Y Bond",
    bondType: "localCurrency",
    currency: "HUF",
    maturity: "10Y",
    couponRate: 5.01,
    bondPrice: 96.4,
    yieldToMaturity: 5.6,
    creditRating: "AA-",
    debtToGdp: 79.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.22,
    exchangeRateVolatility: 5.4,
    foreignExchangeReserves: 230,
    goldReserves: 11.5,
    cdsSpread: 59,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: screenshot; yield basis: local currency.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Romania",
    region: "Europe",
    bondName: "Romania 10Y Bond",
    bondType: "localCurrency",
    currency: "RON",
    maturity: "10Y",
    couponRate: 5.01,
    bondPrice: 96.4,
    yieldToMaturity: 6.8,
    creditRating: "AA-",
    debtToGdp: 79.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.22,
    exchangeRateVolatility: 5.4,
    foreignExchangeReserves: 230,
    goldReserves: 11.5,
    cdsSpread: 59,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: screenshot/public source; yield basis: local currency.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Bulgaria",
    region: "Europe",
    bondName: "Bulgaria 10Y Bond",
    bondType: "localCurrency",
    currency: "BGN",
    maturity: "10Y",
    couponRate: 5.01,
    bondPrice: 96.4,
    yieldToMaturity: 3.7,
    creditRating: "AA-",
    debtToGdp: 79.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.22,
    exchangeRateVolatility: 5.4,
    foreignExchangeReserves: 230,
    goldReserves: 11.5,
    cdsSpread: 59,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: public source; yield basis: local currency.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Slovakia",
    region: "Europe",
    bondName: "Slovakia 10Y Bond",
    bondType: "localCurrency",
    currency: "EUR",
    maturity: "10Y",
    couponRate: 5.01,
    bondPrice: 96.4,
    yieldToMaturity: 3.72,
    creditRating: "AA-",
    debtToGdp: 79.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.22,
    exchangeRateVolatility: 5.4,
    foreignExchangeReserves: 230,
    goldReserves: 11.5,
    cdsSpread: 59,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: screenshot; yield basis: local currency.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Slovenia",
    region: "Europe",
    bondName: "Slovenia 10Y Bond",
    bondType: "localCurrency",
    currency: "EUR",
    maturity: "10Y",
    couponRate: 5.01,
    bondPrice: 96.4,
    yieldToMaturity: 3.2,
    creditRating: "AA-",
    debtToGdp: 79.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.22,
    exchangeRateVolatility: 5.4,
    foreignExchangeReserves: 230,
    goldReserves: 11.5,
    cdsSpread: 59,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: estimate; yield basis: local currency.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Croatia",
    region: "Europe",
    bondName: "Croatia 10Y Bond",
    bondType: "localCurrency",
    currency: "HRK",
    maturity: "10Y",
    couponRate: 5.01,
    bondPrice: 96.4,
    yieldToMaturity: 3.35,
    creditRating: "AA-",
    debtToGdp: 79.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.22,
    exchangeRateVolatility: 5.4,
    foreignExchangeReserves: 230,
    goldReserves: 11.5,
    cdsSpread: 59,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: public source; yield basis: local currency.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Serbia",
    region: "Europe",
    bondName: "Serbia 10Y Bond",
    bondType: "eurobond",
    currency: "RSD",
    maturity: "10Y",
    couponRate: 5.01,
    bondPrice: 96.4,
    yieldToMaturity: 5.8,
    creditRating: "AA-",
    debtToGdp: 79.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.22,
    exchangeRateVolatility: 5.4,
    foreignExchangeReserves: 230,
    goldReserves: 11.5,
    cdsSpread: 59,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: estimate; yield basis: local currency.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Montenegro",
    region: "Europe",
    bondName: "Montenegro 10Y Bond",
    bondType: "eurobond",
    currency: "USD",
    maturity: "10Y",
    couponRate: 5.01,
    bondPrice: 96.4,
    yieldToMaturity: 6,
    creditRating: "AA-",
    debtToGdp: 79.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.22,
    exchangeRateVolatility: 5.4,
    foreignExchangeReserves: 230,
    goldReserves: 11.5,
    cdsSpread: 59,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: estimate; yield basis: USD bond.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "North Macedonia",
    region: "Europe",
    bondName: "North Macedonia 10Y Bond",
    bondType: "eurobond",
    currency: "USD",
    maturity: "10Y",
    couponRate: 5.01,
    bondPrice: 96.4,
    yieldToMaturity: 5.5,
    creditRating: "AA-",
    debtToGdp: 79.4,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.22,
    exchangeRateVolatility: 5.4,
    foreignExchangeReserves: 230,
    goldReserves: 11.5,
    cdsSpread: 59,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: estimate; yield basis: USD bond.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "China",
    region: "Asia",
    bondName: "China 10Y Government Bond",
    bondType: "localCurrency",
    currency: "CNY",
    maturity: "10Y",
    couponRate: 5.46,
    bondPrice: 95.5,
    yieldToMaturity: 1.73,
    creditRating: "A+",
    debtToGdp: 80.9,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 4,
    policyInterestRate: 5.5,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 650,
    goldReserves: 19.5,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: screenshot; yield basis: local currency.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Japan",
    region: "Asia",
    bondName: "Japan 10Y JGB",
    bondType: "localCurrency",
    currency: "JPY",
    maturity: "10Y",
    couponRate: 5.46,
    bondPrice: 95.5,
    yieldToMaturity: 2.73,
    creditRating: "A+",
    debtToGdp: 80.9,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 4,
    policyInterestRate: 5.5,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 650,
    goldReserves: 19.5,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: screenshot; yield basis: local currency.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "South Korea",
    region: "Asia",
    bondName: "South Korea 10Y Bond",
    bondType: "localCurrency",
    currency: "KRW",
    maturity: "10Y",
    couponRate: 5.46,
    bondPrice: 95.5,
    yieldToMaturity: 4.35,
    creditRating: "A+",
    debtToGdp: 80.9,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 4,
    policyInterestRate: 5.5,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 650,
    goldReserves: 19.5,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: screenshot; yield basis: local currency.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "India",
    region: "Asia",
    bondName: "India 10Y G-Sec",
    bondType: "localCurrency",
    currency: "INR",
    maturity: "10Y",
    couponRate: 5.46,
    bondPrice: 95.5,
    yieldToMaturity: 6.95,
    creditRating: "A+",
    debtToGdp: 80.9,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 4,
    policyInterestRate: 5.5,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 650,
    goldReserves: 19.5,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: screenshot; yield basis: local currency.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Indonesia",
    region: "Asia",
    bondName: "Indonesia 10Y Bond",
    bondType: "localCurrency",
    currency: "IDR",
    maturity: "10Y",
    couponRate: 5.46,
    bondPrice: 95.5,
    yieldToMaturity: 7.31,
    creditRating: "A+",
    debtToGdp: 80.9,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 4,
    policyInterestRate: 5.5,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 650,
    goldReserves: 19.5,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: screenshot; yield basis: local currency.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Thailand",
    region: "Asia",
    bondName: "Thailand 10Y Bond",
    bondType: "localCurrency",
    currency: "THB",
    maturity: "10Y",
    couponRate: 5.46,
    bondPrice: 95.5,
    yieldToMaturity: 2.31,
    creditRating: "A+",
    debtToGdp: 80.9,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 4,
    policyInterestRate: 5.5,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 650,
    goldReserves: 19.5,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: screenshot; yield basis: local currency.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Vietnam",
    region: "Asia",
    bondName: "Vietnam 10Y Bond",
    bondType: "localCurrency",
    currency: "VND",
    maturity: "10Y",
    couponRate: 5.46,
    bondPrice: 95.5,
    yieldToMaturity: 4.47,
    creditRating: "A+",
    debtToGdp: 80.9,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 4,
    policyInterestRate: 5.5,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 650,
    goldReserves: 19.5,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: screenshot/public source; yield basis: local currency.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Malaysia",
    region: "Asia",
    bondName: "Malaysia 10Y Bond",
    bondType: "localCurrency",
    currency: "MYR",
    maturity: "10Y",
    couponRate: 5.46,
    bondPrice: 95.5,
    yieldToMaturity: 3.62,
    creditRating: "A+",
    debtToGdp: 80.9,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 4,
    policyInterestRate: 5.5,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 650,
    goldReserves: 19.5,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: screenshot; yield basis: local currency.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Singapore",
    region: "Asia",
    bondName: "Singapore 10Y SGS",
    bondType: "localCurrency",
    currency: "SGD",
    maturity: "10Y",
    couponRate: 5.46,
    bondPrice: 95.5,
    yieldToMaturity: 2.18,
    creditRating: "A+",
    debtToGdp: 80.9,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 4,
    policyInterestRate: 5.5,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 650,
    goldReserves: 19.5,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: screenshot; yield basis: local currency.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Philippines",
    region: "Asia",
    bondName: "Philippines 10Y Bond",
    bondType: "localCurrency",
    currency: "PHP",
    maturity: "10Y",
    couponRate: 5.46,
    bondPrice: 95.5,
    yieldToMaturity: 7.49,
    creditRating: "A+",
    debtToGdp: 80.9,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 4,
    policyInterestRate: 5.5,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 650,
    goldReserves: 19.5,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: screenshot; yield basis: local currency.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Pakistan",
    region: "Asia",
    bondName: "Pakistan 10Y Bond",
    bondType: "eurobond",
    currency: "PKR",
    maturity: "10Y",
    couponRate: 5.46,
    bondPrice: 95.5,
    yieldToMaturity: 12.93,
    creditRating: "A+",
    debtToGdp: 80.9,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 4,
    policyInterestRate: 5.5,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 650,
    goldReserves: 19.5,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: public source; yield basis: local currency.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Bangladesh",
    region: "Asia",
    bondName: "Bangladesh 10Y Bond",
    bondType: "eurobond",
    currency: "BDT",
    maturity: "10Y",
    couponRate: 5.46,
    bondPrice: 95.5,
    yieldToMaturity: 12.05,
    creditRating: "A+",
    debtToGdp: 80.9,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 4,
    policyInterestRate: 5.5,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 650,
    goldReserves: 19.5,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: public source; yield basis: local currency.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Nepal",
    region: "Asia",
    bondName: "Nepal 10Y Bond",
    bondType: "eurobond",
    currency: "NPR",
    maturity: "10Y",
    couponRate: 5.46,
    bondPrice: 95.5,
    yieldToMaturity: 6.5,
    creditRating: "A+",
    debtToGdp: 80.9,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 4,
    policyInterestRate: 5.5,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 650,
    goldReserves: 19.5,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: estimate; yield basis: local currency.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Mongolia",
    region: "Asia",
    bondName: "Mongolia 10Y Bond",
    bondType: "eurobond",
    currency: "USD",
    maturity: "10Y",
    couponRate: 5.46,
    bondPrice: 95.5,
    yieldToMaturity: 7.5,
    creditRating: "A+",
    debtToGdp: 80.9,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 4,
    policyInterestRate: 5.5,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 650,
    goldReserves: 19.5,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: estimate; yield basis: USD bond.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Kazakhstan",
    region: "Asia",
    bondName: "Kazakhstan 10Y Bond",
    bondType: "localCurrency",
    currency: "KZT",
    maturity: "10Y",
    couponRate: 5.46,
    bondPrice: 95.5,
    yieldToMaturity: 13.5,
    creditRating: "A+",
    debtToGdp: 80.9,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 4,
    policyInterestRate: 5.5,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 650,
    goldReserves: 19.5,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: estimate; yield basis: local currency.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Uzbekistan",
    region: "Asia",
    bondName: "Uzbekistan 10Y Bond",
    bondType: "eurobond",
    currency: "USD",
    maturity: "10Y",
    couponRate: 5.46,
    bondPrice: 95.5,
    yieldToMaturity: 7.5,
    creditRating: "A+",
    debtToGdp: 80.9,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 4,
    policyInterestRate: 5.5,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 650,
    goldReserves: 19.5,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: estimate; yield basis: USD bond.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Azerbaijan",
    region: "Asia",
    bondName: "Azerbaijan 10Y Bond",
    bondType: "eurobond",
    currency: "USD",
    maturity: "10Y",
    couponRate: 5.46,
    bondPrice: 95.5,
    yieldToMaturity: 5.5,
    creditRating: "A+",
    debtToGdp: 80.9,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 4,
    policyInterestRate: 5.5,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 650,
    goldReserves: 19.5,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: estimate; yield basis: USD bond.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Georgia",
    region: "Asia",
    bondName: "Georgia 10Y Bond",
    bondType: "eurobond",
    currency: "USD",
    maturity: "10Y",
    couponRate: 5.46,
    bondPrice: 95.5,
    yieldToMaturity: 5,
    creditRating: "A+",
    debtToGdp: 80.9,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 4,
    policyInterestRate: 5.5,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 650,
    goldReserves: 19.5,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: estimate; yield basis: USD bond.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Armenia",
    region: "Asia",
    bondName: "Armenia 10Y Bond",
    bondType: "eurobond",
    currency: "USD",
    maturity: "10Y",
    couponRate: 5.46,
    bondPrice: 95.5,
    yieldToMaturity: 6.5,
    creditRating: "A+",
    debtToGdp: 80.9,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 4,
    policyInterestRate: 5.5,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 650,
    goldReserves: 19.5,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: estimate; yield basis: USD bond.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Saudi Arabia",
    region: "Middle East",
    bondName: "Saudi Arabia 10Y Bond",
    bondType: "localCurrency",
    currency: "USD",
    maturity: "10Y",
    couponRate: 5.6,
    bondPrice: 95.3,
    yieldToMaturity: 5.3,
    creditRating: "A+",
    debtToGdp: 82.4,
    fiscalDeficitToGdp: 3.4,
    inflationRate: 4.1,
    policyInterestRate: 5.66,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 420,
    goldReserves: 6.3,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: estimate; yield basis: USD bond.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "United Arab Emirates",
    region: "Middle East",
    bondName: "UAE 10Y Bond",
    bondType: "eurobond",
    currency: "USD",
    maturity: "10Y",
    couponRate: 5.6,
    bondPrice: 95.3,
    yieldToMaturity: 4.8,
    creditRating: "A+",
    debtToGdp: 82.4,
    fiscalDeficitToGdp: 3.4,
    inflationRate: 4.1,
    policyInterestRate: 5.66,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 420,
    goldReserves: 6.3,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: estimate; yield basis: USD bond.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Qatar",
    region: "Middle East",
    bondName: "Qatar 10Y Bond",
    bondType: "eurobond",
    currency: "USD",
    maturity: "10Y",
    couponRate: 5.6,
    bondPrice: 95.3,
    yieldToMaturity: 4.8,
    creditRating: "A+",
    debtToGdp: 82.4,
    fiscalDeficitToGdp: 3.4,
    inflationRate: 4.1,
    policyInterestRate: 5.66,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 420,
    goldReserves: 6.3,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: estimate; yield basis: USD bond.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Kuwait",
    region: "Middle East",
    bondName: "Kuwait 10Y Bond",
    bondType: "eurobond",
    currency: "USD",
    maturity: "10Y",
    couponRate: 5.6,
    bondPrice: 95.3,
    yieldToMaturity: 5,
    creditRating: "A+",
    debtToGdp: 82.4,
    fiscalDeficitToGdp: 3.4,
    inflationRate: 4.1,
    policyInterestRate: 5.66,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 420,
    goldReserves: 6.3,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: estimate; yield basis: USD bond.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Bahrain",
    region: "Middle East",
    bondName: "Bahrain 10Y Bond",
    bondType: "eurobond",
    currency: "USD",
    maturity: "10Y",
    couponRate: 5.6,
    bondPrice: 95.3,
    yieldToMaturity: 6.5,
    creditRating: "A+",
    debtToGdp: 82.4,
    fiscalDeficitToGdp: 3.4,
    inflationRate: 4.1,
    policyInterestRate: 5.66,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 420,
    goldReserves: 6.3,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: estimate; yield basis: USD bond.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Oman",
    region: "Middle East",
    bondName: "Oman 10Y Bond",
    bondType: "eurobond",
    currency: "USD",
    maturity: "10Y",
    couponRate: 5.6,
    bondPrice: 95.3,
    yieldToMaturity: 4.23,
    creditRating: "A+",
    debtToGdp: 82.4,
    fiscalDeficitToGdp: 3.4,
    inflationRate: 4.1,
    policyInterestRate: 5.66,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 420,
    goldReserves: 6.3,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: public source; yield basis: USD bond.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Israel",
    region: "Middle East",
    bondName: "Israel 10Y Bond",
    bondType: "localCurrency",
    currency: "ILS",
    maturity: "10Y",
    couponRate: 5.6,
    bondPrice: 95.3,
    yieldToMaturity: 3.69,
    creditRating: "A+",
    debtToGdp: 82.4,
    fiscalDeficitToGdp: 3.4,
    inflationRate: 4.1,
    policyInterestRate: 5.66,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 420,
    goldReserves: 6.3,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: screenshot; yield basis: local currency.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Jordan",
    region: "Middle East",
    bondName: "Jordan 10Y Bond",
    bondType: "eurobond",
    currency: "USD",
    maturity: "10Y",
    couponRate: 5.6,
    bondPrice: 95.3,
    yieldToMaturity: 7,
    creditRating: "A+",
    debtToGdp: 82.4,
    fiscalDeficitToGdp: 3.4,
    inflationRate: 4.1,
    policyInterestRate: 5.66,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 420,
    goldReserves: 6.3,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: estimate; yield basis: USD bond.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Iraq",
    region: "Middle East",
    bondName: "Iraq 10Y Bond",
    bondType: "eurobond",
    currency: "USD",
    maturity: "10Y",
    couponRate: 5.6,
    bondPrice: 95.3,
    yieldToMaturity: 7.5,
    creditRating: "A+",
    debtToGdp: 82.4,
    fiscalDeficitToGdp: 3.4,
    inflationRate: 4.1,
    policyInterestRate: 5.66,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 420,
    goldReserves: 6.3,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: estimate; yield basis: USD bond.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "South Africa",
    region: "Africa",
    bondName: "South Africa 10Y Bond",
    bondType: "localCurrency",
    currency: "ZAR",
    maturity: "10Y",
    couponRate: 5.68,
    bondPrice: 95.2,
    yieldToMaturity: 8.74,
    creditRating: "A+",
    debtToGdp: 83.4,
    fiscalDeficitToGdp: 3.5,
    inflationRate: 4.1,
    policyInterestRate: 5.72,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 80,
    goldReserves: 1.2,
    cdsSpread: 71,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: screenshot; yield basis: local currency.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Nigeria",
    region: "Africa",
    bondName: "Nigeria 10Y Bond",
    bondType: "eurobond",
    currency: "NGN",
    maturity: "10Y",
    couponRate: 5.68,
    bondPrice: 95.2,
    yieldToMaturity: 14.96,
    creditRating: "A+",
    debtToGdp: 83.4,
    fiscalDeficitToGdp: 3.5,
    inflationRate: 4.1,
    policyInterestRate: 5.72,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 80,
    goldReserves: 1.2,
    cdsSpread: 71,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: public source; yield basis: local currency.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Egypt",
    region: "Africa",
    bondName: "Egypt 10Y Bond",
    bondType: "eurobond",
    currency: "EGP",
    maturity: "10Y",
    couponRate: 5.68,
    bondPrice: 95.2,
    yieldToMaturity: 21,
    creditRating: "A+",
    debtToGdp: 83.4,
    fiscalDeficitToGdp: 3.5,
    inflationRate: 4.1,
    policyInterestRate: 5.72,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 80,
    goldReserves: 1.2,
    cdsSpread: 71,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: public source; yield basis: local currency.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Morocco",
    region: "Africa",
    bondName: "Morocco 10Y Bond",
    bondType: "eurobond",
    currency: "MAD",
    maturity: "10Y",
    couponRate: 5.68,
    bondPrice: 95.2,
    yieldToMaturity: 2.96,
    creditRating: "A+",
    debtToGdp: 83.4,
    fiscalDeficitToGdp: 3.5,
    inflationRate: 4.1,
    policyInterestRate: 5.72,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 80,
    goldReserves: 1.2,
    cdsSpread: 71,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: public source; yield basis: local currency.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Algeria",
    region: "Africa",
    bondName: "Algeria 10Y Bond",
    bondType: "eurobond",
    currency: "DZD",
    maturity: "10Y",
    couponRate: 5.68,
    bondPrice: 95.2,
    yieldToMaturity: 4.5,
    creditRating: "A+",
    debtToGdp: 83.4,
    fiscalDeficitToGdp: 3.5,
    inflationRate: 4.1,
    policyInterestRate: 5.72,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 80,
    goldReserves: 1.2,
    cdsSpread: 71,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: estimate; yield basis: local currency.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Tunisia",
    region: "Africa",
    bondName: "Tunisia 10Y Bond",
    bondType: "eurobond",
    currency: "USD",
    maturity: "10Y",
    couponRate: 5.68,
    bondPrice: 95.2,
    yieldToMaturity: 10,
    creditRating: "A+",
    debtToGdp: 83.4,
    fiscalDeficitToGdp: 3.5,
    inflationRate: 4.1,
    policyInterestRate: 5.72,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 80,
    goldReserves: 1.2,
    cdsSpread: 71,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: estimate; yield basis: USD bond.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Kenya",
    region: "Africa",
    bondName: "Kenya 10Y Bond",
    bondType: "eurobond",
    currency: "KES",
    maturity: "10Y",
    couponRate: 5.68,
    bondPrice: 95.2,
    yieldToMaturity: 12.2,
    creditRating: "A+",
    debtToGdp: 83.4,
    fiscalDeficitToGdp: 3.5,
    inflationRate: 4.1,
    policyInterestRate: 5.72,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 80,
    goldReserves: 1.2,
    cdsSpread: 71,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: public source; yield basis: local currency.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Tanzania",
    region: "Africa",
    bondName: "Tanzania 10Y Bond",
    bondType: "eurobond",
    currency: "TZS",
    maturity: "10Y",
    couponRate: 5.68,
    bondPrice: 95.2,
    yieldToMaturity: 14,
    creditRating: "A+",
    debtToGdp: 83.4,
    fiscalDeficitToGdp: 3.5,
    inflationRate: 4.1,
    policyInterestRate: 5.72,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 80,
    goldReserves: 1.2,
    cdsSpread: 71,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: estimate; yield basis: local currency.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Uganda",
    region: "Africa",
    bondName: "Uganda 10Y Bond",
    bondType: "eurobond",
    currency: "UGX",
    maturity: "10Y",
    couponRate: 5.68,
    bondPrice: 95.2,
    yieldToMaturity: 16,
    creditRating: "A+",
    debtToGdp: 83.4,
    fiscalDeficitToGdp: 3.5,
    inflationRate: 4.1,
    policyInterestRate: 5.72,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 80,
    goldReserves: 1.2,
    cdsSpread: 71,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: 估算/网络; yield basis: local currency.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Angola",
    region: "Africa",
    bondName: "Angola 10Y Bond",
    bondType: "eurobond",
    currency: "USD",
    maturity: "10Y",
    couponRate: 5.68,
    bondPrice: 95.2,
    yieldToMaturity: 10,
    creditRating: "A+",
    debtToGdp: 83.4,
    fiscalDeficitToGdp: 3.5,
    inflationRate: 4.1,
    policyInterestRate: 5.72,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 80,
    goldReserves: 1.2,
    cdsSpread: 71,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: estimate; yield basis: USD bond.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Mozambique",
    region: "Africa",
    bondName: "Mozambique 10Y Bond",
    bondType: "eurobond",
    currency: "USD",
    maturity: "10Y",
    couponRate: 5.68,
    bondPrice: 95.2,
    yieldToMaturity: 11,
    creditRating: "A+",
    debtToGdp: 83.4,
    fiscalDeficitToGdp: 3.5,
    inflationRate: 4.1,
    policyInterestRate: 5.72,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 80,
    goldReserves: 1.2,
    cdsSpread: 71,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: estimate; yield basis: USD bond.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Senegal",
    region: "Africa",
    bondName: "Senegal 10Y Bond",
    bondType: "eurobond",
    currency: "USD",
    maturity: "10Y",
    couponRate: 5.68,
    bondPrice: 95.2,
    yieldToMaturity: 8,
    creditRating: "A+",
    debtToGdp: 83.4,
    fiscalDeficitToGdp: 3.5,
    inflationRate: 4.1,
    policyInterestRate: 5.72,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 80,
    goldReserves: 1.2,
    cdsSpread: 71,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: estimate; yield basis: USD bond.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Cameroon",
    region: "Africa",
    bondName: "Cameroon 10Y Bond",
    bondType: "eurobond",
    currency: "USD",
    maturity: "10Y",
    couponRate: 5.68,
    bondPrice: 95.2,
    yieldToMaturity: 9,
    creditRating: "A+",
    debtToGdp: 83.4,
    fiscalDeficitToGdp: 3.5,
    inflationRate: 4.1,
    policyInterestRate: 5.72,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 80,
    goldReserves: 1.2,
    cdsSpread: 71,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: estimate; yield basis: USD bond.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Botswana",
    region: "Africa",
    bondName: "Botswana 10Y Bond",
    bondType: "eurobond",
    currency: "BWP",
    maturity: "10Y",
    couponRate: 5.68,
    bondPrice: 95.2,
    yieldToMaturity: 5.5,
    creditRating: "A+",
    debtToGdp: 83.4,
    fiscalDeficitToGdp: 3.5,
    inflationRate: 4.1,
    policyInterestRate: 5.72,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 80,
    goldReserves: 1.2,
    cdsSpread: 71,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: estimate; yield basis: local currency.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Namibia",
    region: "Africa",
    bondName: "Namibia 10Y Bond",
    bondType: "eurobond",
    currency: "NAD",
    maturity: "10Y",
    couponRate: 5.68,
    bondPrice: 95.2,
    yieldToMaturity: 10,
    creditRating: "A+",
    debtToGdp: 83.4,
    fiscalDeficitToGdp: 3.5,
    inflationRate: 4.1,
    policyInterestRate: 5.72,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 80,
    goldReserves: 1.2,
    cdsSpread: 71,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: estimate; yield basis: local currency.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Mauritius",
    region: "Africa",
    bondName: "Mauritius 10Y Bond",
    bondType: "eurobond",
    currency: "MUR",
    maturity: "10Y",
    couponRate: 5.68,
    bondPrice: 95.2,
    yieldToMaturity: 5,
    creditRating: "A+",
    debtToGdp: 83.4,
    fiscalDeficitToGdp: 3.5,
    inflationRate: 4.1,
    policyInterestRate: 5.72,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 80,
    goldReserves: 1.2,
    cdsSpread: 71,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: estimate; yield basis: local currency.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Rwanda",
    region: "Africa",
    bondName: "Rwanda 10Y Bond",
    bondType: "eurobond",
    currency: "USD",
    maturity: "10Y",
    couponRate: 5.68,
    bondPrice: 95.2,
    yieldToMaturity: 9,
    creditRating: "A+",
    debtToGdp: 83.4,
    fiscalDeficitToGdp: 3.5,
    inflationRate: 4.1,
    policyInterestRate: 5.72,
    exchangeRateVolatility: 5.8,
    foreignExchangeReserves: 80,
    goldReserves: 1.2,
    cdsSpread: 71,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: estimate; yield basis: USD bond.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Australia",
    region: "Oceania",
    bondName: "Australia 10Y Bond",
    bondType: "localCurrency",
    currency: "AUD",
    maturity: "10Y",
    couponRate: 5.36,
    bondPrice: 95.6,
    yieldToMaturity: 4.96,
    creditRating: "A+",
    debtToGdp: 79.9,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.38,
    exchangeRateVolatility: 6.2,
    foreignExchangeReserves: 30,
    goldReserves: 0.6,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: screenshot; yield basis: local currency.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "New Zealand",
    region: "Oceania",
    bondName: "New Zealand 10Y Bond",
    bondType: "localCurrency",
    currency: "NZD",
    maturity: "10Y",
    couponRate: 5.36,
    bondPrice: 95.6,
    yieldToMaturity: 4.63,
    creditRating: "A+",
    debtToGdp: 79.9,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.38,
    exchangeRateVolatility: 6.2,
    foreignExchangeReserves: 30,
    goldReserves: 0.6,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: screenshot; yield basis: local currency.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Papua New Guinea",
    region: "Oceania",
    bondName: "Papua New Guinea 10Y Bond",
    bondType: "eurobond",
    currency: "PGK",
    maturity: "10Y",
    couponRate: 5.36,
    bondPrice: 95.6,
    yieldToMaturity: 9.5,
    creditRating: "A+",
    debtToGdp: 79.9,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.38,
    exchangeRateVolatility: 6.2,
    foreignExchangeReserves: 30,
    goldReserves: 0.6,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: estimate; yield basis: local currency.",
    lastUpdated: "2026-06-08"
  },
  {
    country: "Fiji",
    region: "Oceania",
    bondName: "Fiji 10Y Bond",
    bondType: "eurobond",
    currency: "FJD",
    maturity: "10Y",
    couponRate: 5.36,
    bondPrice: 95.6,
    yieldToMaturity: 5.5,
    creditRating: "A+",
    debtToGdp: 79.9,
    fiscalDeficitToGdp: 3.3,
    inflationRate: 3.9,
    policyInterestRate: 5.38,
    exchangeRateVolatility: 6.2,
    foreignExchangeReserves: 30,
    goldReserves: 0.6,
    cdsSpread: 70,
    liquidityBidAskSpread: 0.03,
    sourceNote: "10Y YTM from 2026-06-08 Excel workbook; source: estimate; yield basis: local currency.",
    lastUpdated: "2026-06-08"
  }
];
